class HTTP_METHODS:
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    PATCH = "PATCH"
    HEAD = "HEAD"
    OPTIONS = "OPTIONS"


class HTTP_CODE:
    OK = 200
    SEE_OTHER = 303
    TEMPORARY_REDIRECT = 307
    NOT_FOUND = 404
